// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:0f1b4f91-8b72-49f6-95c9-6976fa6f55ee",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_rTRHIQunk",
    "aws_user_pools_web_client_id": "1mk6tusfoo2du241q9h27jqd0d",
    "aws_user_files_s3_bucket": "hbreduxapp78749a97f27e4559ae86233913e13248",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
